name: geko_player
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  media_kit_video: ^1.2.4
  media_kit: ^1.1.10+1
  media_kit_libs_video: ^1.0.4
  path_provider: ^2.1.4
  file_picker: ^8.0.6
  path: ^1.9.0
  process_run: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  msix: ^3.16.7
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
#flutter pub run flutter_launcher_icons
  windows:
      generate: true
      image_path: "assets/logo-base.png"
      icon_size: 48
#dart run msix:create
msix_config:
  display_name: Geko Player
  publisher_display_name: Gekode
  identity_name: gekode.gekoplayer
  certificate_path: C:\Users\ropor\Documents\pxf\certificate.pfx
  certificate_password: 651420
  install_certificate: true
  msix_version: 1.0.0.0
  store: false

flutter:
  uses-material-design: true
  assets:
    - tools/ffmpeg.exe
    - assets/logo-base.png